init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

skip_tags: true

environment:
  matrix:
    - nodejs_version: '1'
    - nodejs_version: '0'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install tape

build: off

test_script:
  - ps: node test.js
  - cmd: node test.js

cache:
  - node_modules
